### ISSUE TITLE
FLT support documentation

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/formulate#104]
**USE THIS TICKET OR TICKET 153, NOT BOTH**

Once we meet with the Design systems team, create an artifact that lives in confluence that outlines boundaries 

Task is done when: we have a link to a completed artifact.

**Comment by ken-non** [comment]
This is delayed - will wait on making a formal decision until we know if we're building or greenfielding. if building, we'll need it.

**Comment by taylorkaren** [comment]
Work for this will be handled on ticket #153.
