### ISSUE TITLE
Analysis: Fix vs Greenfield

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/formulate#105]
We have a lot research in disparate places, we need to gather information into a centralized doc ( [example](https://vfs.atlassian.net/wiki/spaces/AMT/pages/1959067732/Identity+Broker+Decision) ) to figure out next steps. 

**Tasks**
- [x] Decide on criteria
- [x] Meet with team to add fix and greenfield details for criteria
- [x] Finalize document

**Task is done when:** 
We have entered all of the information on this Confluence page: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2063663453/Analysis+Fix+vs+Greenfield+WIP

**Comment by taylorkaren** [comment]
Confluence page: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2063663453/Decision+Fix+vs+Greenfield.

**Comment by taylorkaren** [comment]
Document finalized during 2/3/22 team meeting.
