### ISSUE TITLE
Forms Library documentation migration and recommendations

### ISSUE THREAD

**Issue by ken-non** [department-of-veterans-affairs/formulate#106]
Create a systematic record of existing Forms Library documentation and recommendations for consolidating and updating documentation on the new documentation hub (https://depo-platform-documentation.scrollhelp.site/index.html).

**Task is done when**
Documentation is reviewed and accepted by:
- [x] Komes Komes 
- [x] BJ McCotter 
- [x] Susanna Kline 
- [x] Karen Taylor

**Comment by micahchiang** [comment]
spreadsheet here - https://docs.google.com/spreadsheets/d/1V7T8iTBFNFB96WDzidavryxCuxgYe56EDjTuPVIXscE/edit#gid=0

**Comment by taylorkaren** [comment]
See if this supersedes #97 - if yes, transfer any useful information from #97 to this ticket.

**Comment by sdk-irl** [comment]
Note that when updating this, we should also consider all the info in this PR that Katy sent Micah: https://github.com/department-of-veterans-affairs/veteran-facing-services-tools/pull/349/files
Now nted in another ticket here: https://app.zenhub.com/workspaces/forms-library---platform-spike-team-61b0ae1f2cd3c30014e8a5b0/issues/department-of-veterans-affairs/formulate/116
