### ISSUE TITLE
Documentation Work: Bypassing schemaForm

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/formulate#160]
Looks like we missed writing a ticket for this - it's on the [Documentation Log sheet](https://docs.google.com/spreadsheets/d/1V7T8iTBFNFB96WDzidavryxCuxgYe56EDjTuPVIXscE/edit#gid=0) as something to move over.

Current documentation is here: https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/bypassing-schemaform/.

**Comment by bkjohnson** [comment]
There is also this: https://department-of-veterans-affairs.github.io/formulate/how-to-guides/how-to-integrate-with-old-forms.html

**Comment by taylorkaren** [comment]
Added Brooks' comment to 130. This ticket duplicates 130, so closing this one.
