### ISSUE TITLE
Forms Library Team Initial Research and Discover

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/formulate#56]
## Description
_This ticket is a placeholder until our board and sprint flow is more formalized_

With the Forms Library Spike Team (FLT) ramping up, the first part of our process is conducting research into how things currently work. Regardless of the answer to the question "Will we build anew or iterate on what we have?", a strong working knowledge of how the existing forms library works will be critical to building for success. 

## Considerations
- Our first official sprint kicks off on Thursday 12/9 so our official board is still in progress and more concrete tickets will be created later this week. 
- [FLT confluence space](https://vfs.atlassian.net/wiki/spaces/FLT/overview?homepageId=1992458316) where our starter task has lived, and all product, engineering, and research documentation will live going forward.

## Tasks 
- [ ] Conduct research into strengths and weaknesses of the existing forms library
- [ ] Evaluate work already done on [Formulate](https://github.com/department-of-veterans-affairs/formulate)

**Comment by taylorkaren** [comment]
This looks good to me, Micah. Thanks for putting it together.

**Comment by taylorkaren** [comment]
The tasks on this issue are now covered by other individual issues.
