### ISSUE TITLE
(Hold for Micah review) Forms inventory and product list

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/formulate#59]
## Task Description
Find or create a forms inventory and product list to document which forms on the va.gov site are using the Forms Library and which are not.

We want to know:
**ADD MORE THINGS AS WE THINK OF THEM**
- What forms are on the va.gov site and where are they (URLs)?
-- If the same form appears in multiple locations on the site, is it really the same form or are there variations depending on location?
- Does the form use the current Forms Library?
-- If no, what does it use (how was it built)?

### Research Resources
- Slack thread from Brooks with a list of apps currently using the Forms Library: https://dsva.slack.com/archives/C01DBGX4P45/p1637337872034000?thread_ts=1637326827.031900&cid=C01DBGX4P45
- Registry.json file in the content build repo - should be a list of all React Apps on VA.gov Home | Veterans Affairs

### Why this?
- This will help us get a sense of what the migration landscape for forms using the current Forms Library would look like.
- This will also help us get a sense of the characteristics of forms that are not using the current Forms Library, and inform the definition of a form that will be developed via #58.

## Acceptance Criteria
- [x] Research has been synthesized into a Confluence document in the FLT workspace
- [x] That Confluence document includes an inventory list of forms on the va.gov site with details for each form as listed above in the "We want to know" bullet points.

**Comment by taylorkaren** [comment]
Status from Komes on 12/14, before going on vacation: All of the applications that use form library are done and marked as “yes” on the column “use form library”. For the ones that do not use form library, some are done being reviewed, some are still in the process and will be marked on the ‘note’ column as TBD. I will continue to work on them though today. I can finish the ones that marked TBD when I come back. Please feel free to have anyone change or update anything as you see fit. Thank you.

**Comment by bkjohnson** [comment]
@bjmccotter7192 these yarn scripts may be useful for you: https://github.com/department-of-veterans-affairs/design-system-dashboard-cli#generate-a-report-of-forms-library-applications

**Comment by bjmccotter7192** [comment]
@bkjohnson Thank you I appreciate that a ton!

**Comment by bjmccotter7192** [comment]
Finished updating all of the "TBD" elements in the table with high level notes for each form not using the forms system currently. Any additional information can be conducted once I come back from vacation.

**Comment by taylorkaren** [comment]
Komes will finish reviewing this page and making updates today.

**Comment by kkomes** [comment]
Finished reviewing form inventory.

**Comment by taylorkaren** [comment]
Review notes for @bjmccotter7192 and @kkomes:

- There are two apps on the list from Brooks (https://dsva.slack.com/archives/C01DBGX4P45/p1637337872034000?thread_ts=1637326827.031900&cid=C01DBGX4P45) that I don't see on the page: Contact Us and Search representative. Is there a reason why they were excluded?
- GitHub repo link is missing for My Health Account Validation.
- Discharge wizard is missing a Yes/No designation in the "Use Forms Library" column.

**Comment by kkomes** [comment]
This name of two apps from Brooks are different from the name in registry.json

For "Contact Us", the name in registry.json is 
"Apply for Personalized Career Planning and Guidance with VA Form 28-8832"

For "Search representative", the name in registry.json is 
"View your representative"

I have now put the names from Brook in parenthesis for both apps in Confluence document.

For "My Health Account Validation", the URL provided in registry.json is invalid. So we could not search fro Github repo link.
