### ISSUE TITLE
(Micah to schedule Part 2) Web components integration into the current Forms Library

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/formulate#60]
## Task Description
What does it take to integrate Design System web components into a form using the current Forms Library?

Plan is to have a mob programming session on this during the week of 12/27. 
Record the session and take notes for compilation on a Confluence page.

### Why this?
Being able to easily use web components within the Forms Library would provide a wider range of functionality to support use cases above and beyond basic, plain vanilla forms.

## Considerations
- [confluence page about customPage](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2012512257/Bypassing+Schemaform+with+CustomPage+and+CustomPageReview)
- look at using ui:widget or ui:field as a means to bypass schemaform defaults

## Acceptance Criteria
- [ ] Research has been synthesized into a Confluence document in the FLT workspace that includes a link to the mob programming session recording.
- [ ] That Confluence document includes a summary of the investigation activities, degree of ease or difficulty to integrate Design System web components into a form using the current Forms Library, and suggestions for improving how this works (if applicable).

**Comment by taylorkaren** [comment]
Meeting scheduled for 11/29/21.

**Comment by taylorkaren** [comment]
Confluence page (with recording) with notes from the 12/29/21 session: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2031485087/Notes+from+Mob+session+12+29+on+Available+form+widgets+docs.

**Comment by micahchiang** [comment]
Recurring mob sessions have been scheduled for every other Wednesday.

**Comment by ken-non** [comment]
were able to integrate a web component but stuck on attaching an event handler

**Comment by ken-non** [comment]
[Mob Session 12 January 2022](https://vfs.atlassian.net/wiki/spaces/FLT/pages/2048884804/Mob+Session+1+12+2022)
