### ISSUE TITLE
Use the React bindings from the component library

### ISSUE THREAD

**Issue by cvalarida** [department-of-veterans-affairs/formulate#7]
## Description
The web components [release version 0.9.2](https://github.com/department-of-veterans-affairs/component-library/releases/tag/wc-v0.9.2) now contains React bindings for the web components, so we can use them in formulate instead of making our own.

## Acceptance criteria
- [ ] The `TextField` imports the React bindings for the `va-text-input`
- [ ] The `CheckboxField` imports the React bindings for the `va-checkbox`

**Comment by bkjohnson** [comment]
#16 updates the `web-components` dependency to a version where the bindings are available. It also uses the `VaSelect` binding.
