### ISSUE TITLE
Craft findings/recommendations doc

### ISSUE THREAD

**Issue by laurylzenobi** [department-of-veterans-affairs/formulate#73]
The research team will synthesize past research and discovery research results into a findings and recommendations doc. This will be used along with technical discovery research to scope how much discovery is needed in Jan 2022. 

acceptance criteria:

- [ ] Complete analysis
- [ ] Findings and recommendations doc developed and reviewed by UX team
- [ ] Final doc is added to confluence

**Comment by biannuz** [comment]
Confluence doc here: https://vfs.atlassian.net/l/c/1h50H9RG
