### ISSUE TITLE
Evaluate Formulate

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/formulate#77]
## Description
In order for our team to gain a better understanding of which direction we need to go, we have to evaluate what already exists in Formulate. 

## Acceptance Criteria

**Comment by taylorkaren** [comment]
Does this duplicate #72?

**Comment by micahchiang** [comment]
Ah yes it does! Sorry, didn't see that one as I was moving around the board. I'll close this 👍
