### ISSUE TITLE
Review documentation for other design systems

### ISSUE THREAD

**Issue by taylorkaren** [department-of-veterans-affairs/formulate#79]
## Task Description
Take a look at other Design System and Forms System documentation for ideas on how to present documentation for the new Forms Library.

### Why this?
So that we have a sense of the information that is included in other design systems and how it is presented as we think about what the documentation could be like for a new Forms Library.

### Review Candidates
_US Web Design System_
- Overview: [How to use USWDS | U.S. Web Design System (USWDS)](https://designsystem.digital.gov/how-to-use-uswds/)
- Form templates: [Form templates | U.S. Web Design System (USWDS)](https://designsystem.digital.gov/templates/form-templates/) 
- Align what we are doing with what USDS does in terms of coding conventions and guidelines?

_US Forms System Documentation_
- https://github.com/usds/us-forms-system/blob/master/docs/README.md

_CMS Design System_:
- [CMS Design System | An open source design and front-end toolkit](https://design.cms.gov/) 
- [Forms: Forms - CMS Design System](https://design.cms.gov/guidelines/forms/) 

_NASA Web Design System_ 
- [NASA Web Design System: A design system for NASA](https://nasa.github.io/nasawds-site/)  
-- Some content outdated, look at for IA

## Acceptance Criteria
- [x] The findings from reviewing other design system documentation has been synthesized in a Confluence document in the FLT workspace. 

### Documentation is reviewed and accepted by:
- [x] Micah Chiang 
- [x] Komes Komes 
- [x] BJ McCotter 
- [x] Susanna Kline 
- [x] Karen Taylor / Kennon Hulett

**Comment by sdk-irl** [comment]
@taylorkaren @micahchiang I completed the analysis of these four sites. There was a lot to look at, not all of which was entirely relevant to us, so I made a lot of notes but tried to edit the irrelevant parts. If you have any questions (especially if it seems like I've edited something out, and it is now unclear) please let me know, and I'll fix it.  https://vfs.atlassian.net/l/c/QtL0B2n1

**Comment by taylorkaren** [comment]
I think this looks great, @sdk-irl! We can talk more in standup today.

**Comment by micahchiang** [comment]
Looks fantastic @sdk-irl great job!
