### ISSUE TITLE
Accessibility Training

### ISSUE THREAD

**Issue by bjmccotter7192** [department-of-veterans-affairs/formulate#80]
Any training towards accessibility such as:

- Udacity
- Deque
- Udemy

## Acceptance criteria
- Each person to whom the ticket is assigned to document what they have done to complete a11y levels as outlined [a11y champions curriculum](https://docs.google.com/document/d/1-2W9Gm97lBWWv8ljjjQ20JJEHS4DF8ldqHBIY4yWhFs/edit#heading=h.o1b49rfssykx)

**Comment by sdk-irl** [comment]
Susanna:
- Completed Ad Hoc Level 2 Accessibility Champions Course
- 1/8 of the way through the Web Accessibility Curriculum and the IAAP WAS Certification Preparation Curriculum 2.0

**Comment by kkomes** [comment]
Completed Ad Hoc Level 1 Accessibility Champions Course
