### ISSUE TITLE
(Add link to example form on the Confluence page) Research react-hook-forms

### ISSUE THREAD

**Issue by sdk-irl** [department-of-veterans-affairs/formulate#81]
### Task Description
Research react-hook-forms library as a potential open source alternative. Find pros and cons of this option by creating a small form. Potentially compare to formik and/or to the current library. 

Link to confluence page comparing pros and cons:
https://vfs.atlassian.net/wiki/spaces/FLT/pages/2017493095/react-hook-form

### Acceptance Criteria
- [x] Compile research tasks and the pros and cons of react-hook-forms in a Confluence document
- [x] Include a link to the Confluence document on this ticket

**Comment by taylorkaren** [comment]
Confluence link: https://vfs.atlassian.net/wiki/spaces/FLT/pages/2017493095/react-hook-form

**Comment by taylorkaren** [comment]
Susanna will add a link to the form she created to the Confluence page.

**Comment by sdk-irl** [comment]
@taylorkaren I added the code for a simple form to the document and a link to a visual demo for how it works. It made a little more sense than spending time deploying it somewhere since we haven't decided what we're doing yet. I also added another Con that I thought of after going to more research sessions and delving into the component library a bit more

**Comment by taylorkaren** [comment]
@sdk-irl: Did you publish the updates to that Confluence page? It still has an updated date of Dec 17 when I look at it.
