### ISSUE TITLE
Analyze gaps of VA.gov client application documentation site

### ISSUE THREAD

**Issue by micahchiang** [department-of-veterans-affairs/formulate#85]
## Description
A recurring theme in past and current research is the vast deficit of up to date documentation around how the forms library currently works. We should analyze what is missing and address any gaps in documentation around existing features of the forms library. 

## Considerations
- [documentation site](http://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms)
- We _may_ need codeowners access to manage PRs
- it's gatsby site
-- Note that there is an open issue to [Build the docs in CI](https://github.com/department-of-veterans-affairs/va.gov-team/issues/27436)
 - Karen took a look at this site early on - notes from that review would be a good input to this task: https://docs.google.com/document/d/1EGl8t3G8_2SwCtoFzXYFwbVF2f8a1dDDC2HI6U5lFU4/edit#heading=h.8znyz668zjua
- Save in progress is not documented at all (per 12/13 DST team sync call - Setting this property to True does not automatically trigger this functionality, that should be documented: https://docs.google.com/document/d/1uM5SdQLhqAAtmsMRh6b9esE52txmW3MrxyLmNvaPrpQ/edit#heading=h.nojbz4t7t4d2).
- Something that needs to be fixed: https://github.com/department-of-veterans-affairs/va.gov-team/issues/12479.
- What do we mean by form patterns? 
-- There is a [Common patterns for building forms page](https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms/common-patterns-for-building-forms), but that's not the same sort of form pattern discussed on this ticket: https://github.com/department-of-veterans-affairs/va.gov-team/issues/32437 (or on the sheet linked to that ticket: https://docs.google.com/spreadsheets/d/1_ml9wTnqhQHcrmS728AsGeZ34OdR67Gp0dJn1Wh3-FA/edit?usp=sharing.
- From the [Forms inventory and product list](https://vfs.atlassian.net/wiki/spaces/FLT/pages/edit-v2/2017493166): "Need better documentation around the schemaForm compared to the formConfig json object."
- Additional documentation and sources that may be of help when addressing the identified gaps are documented on #95.

## Acceptance Criteria 
- [ ] list compiled of areas for improvement (this will be used to write tickets to make updates to the documentation site)

**Comment by bjmccotter7192** [comment]
Quick note: Noticed that when navigating on https://department-of-veterans-affairs.github.io/veteran-facing-services-tools/forms if you click on "Components" link in the navigation bar, you will get redirected to https://design.va.gov/components/. This causes some issues because it is really hard to find a way back to the original forms system documentation page. 

Questions: 
- Should we have the forms system documentation on design.va.gov? 
- Should there be a link back to the internal github page for the forms system from the design.va.gov/components?

**Comment by taylorkaren** [comment]
Per 1/10/22 standup discussion, Micah to review and close.

**Comment by micahchiang** [comment]
Page in confluence looks great. Nice job @sdk-irl !
